CREATE TABLE IF NOT EXISTS public.campaign_invite
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    campaign_id bigint NOT NULL,
    hash uuid NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT campaign_invite_pkey PRIMARY KEY (id),
    CONSTRAINT campaign_invite_campaign_id_key UNIQUE (campaign_id)
    CONSTRAINT fk_campaign_campaign_invite FOREIGN KEY (campaign_id)
        REFERENCES public.campaign (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);