CREATE TABLE IF NOT EXISTS public.session
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    campaign_id bigint NOT NULL,
    date date NOT NULL DEFAULT now(),
    CONSTRAINT session_pkey PRIMARY KEY (id),
    CONSTRAINT fk_campaign_session FOREIGN KEY (campaign_id)
        REFERENCES public.campaign (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

