// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/core/api/v1/campaign": {
            "get": {
                "description": "Get a page of the current user campaigns as **player** and **DM**, ordered by name (ignoring case and accents), then id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:campaign"
                ],
                "summary": "Get current user campaigns",
                "parameters": [
                    {
                        "enum": [
                            "dm",
                            "player"
                        ],
                        "type": "string",
                        "description": "Only campaigns where the user has this role",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "DRAFT",
                            "ACTIVE",
                            "PAUSED",
                            "ARCHIVED"
                        ],
                        "type": "string",
                        "description": "Only campaigns with this status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Page size, 1 to 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of campaigns to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/campaign.CampaignListPageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid role, status, limit or offset",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "post": {
                "description": "Create new campaign with status **DRAFT**",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:campaign"
                ],
                "summary": "Create campaign",
                "parameters": [
                    {
                        "description": "Campaign data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/campaign.CreateCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rpg.RpgSlugResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid campaign data",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/campaign/counts": {
            "get": {
                "description": "Number of the current user campaigns in each status. Every status is present, with 0 when there is none",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:campaign"
                ],
                "summary": "Get current user campaign counts by status",
                "parameters": [
                    {
                        "enum": [
                            "dm",
                            "player"
                        ],
                        "type": "string",
                        "description": "Only campaigns where the user has this role",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/campaign.CampaignStatusCountsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/campaign/resolve/{slug}": {
            "get": {
                "description": "Resolves the campaign slug to the internal ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:campaign"
                ],
                "summary": "Resolve campaign slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rpg.RpgIdResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid slug",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Campaign not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/campaign/{campaignID}": {
            "get": {
                "description": "Get a more detailed view of the campaign. Only the DM and players with a character in the campaign can see it, and only the DM gets the invite hash",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:campaign"
                ],
                "summary": "Get campaign details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/campaign.CampaignDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Not a member of this campaign",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Campaign not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "Deletes a campaign with the status **ARCHIVED** or **DRAFT**",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:campaign"
                ],
                "summary": "Delete campaign",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Only the DM can delete a campaign",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Campaign not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/campaign/{campaignID}/status": {
            "patch": {
                "description": "Updates campaign status to the following rules:\n- **DRAFT** -\u003e ACTIVE\n- **ACTIVE** -\u003e PAUSED / ARCHIVED\n- **PAUSED** -\u003e ACTIVE / ARCHIVED",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:campaign"
                ],
                "summary": "Update Status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New campaign status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/campaign.UpdateCampaignStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/campaign.CampaignStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Only the DM can update a campaign, or the status transition is invalid",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Campaign not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/character": {
            "get": {
                "description": "Get a page of the current user characters, ordered by name (ignoring case and accents), then id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:character"
                ],
                "summary": "Get current user characters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Only characters of this game system",
                        "name": "game_system",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "true: only characters without a campaign; false: only characters in a campaign",
                        "name": "without_campaign",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Page size, 1 to 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of characters to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/character.CharacterListPageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid game_system, limit or offset",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "post": {
                "description": "Create new character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:character"
                ],
                "summary": "Create character",
                "parameters": [
                    {
                        "description": "Character data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/character.CreateCharacterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rpg.RpgSlugResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid character data",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/character/resolve/{slug}": {
            "get": {
                "description": "Resolves the character slug to the internal ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:character"
                ],
                "summary": "Resolve character slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Character slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rpg.RpgIdResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid slug",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Character not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/character/{characterID}": {
            "get": {
                "description": "Get a more detailed view of the character",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:character"
                ],
                "summary": "Get character details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Character ID",
                        "name": "characterID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/character.CharacterDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Character not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "Deletes a character",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:character"
                ],
                "summary": "Delete character",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Character ID",
                        "name": "characterID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Only the player can delete a character",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Character not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/character/{characterID}/hp": {
            "patch": {
                "description": "Updates character HP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:character"
                ],
                "summary": "Update HP",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Character ID",
                        "name": "characterID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New character HP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/character.UpdateHPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/character.CharacterCurrentHpResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Only the character's player can update it",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Character not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/invite": {
            "post": {
                "description": "Create a new campaign invite",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:invite"
                ],
                "summary": "Create campaign invite",
                "parameters": [
                    {
                        "description": "Invite data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/invite.CreateInviteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/invite.InviteCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Campaign is archived",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "Only the DM can create a campaign invite",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Campaign not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "409": {
                        "description": "Invite for campaign already exists",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/invite/{inviteHash}": {
            "get": {
                "description": "Gets the invite's campaign details (name, overview, game system, player count) for any user holding the hash. ` + "`" + `is_dm` + "`" + ` tells whether the requester is the campaign DM, who can't accept the invite",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:invite"
                ],
                "summary": "Get campaign invite details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invite hash",
                        "name": "inviteHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/invite.InviteDetailsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Invite not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/invite/{inviteHash}/accept": {
            "post": {
                "description": "Accepts campaign invite linking selected character to campaign",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:invite"
                ],
                "summary": "Accept invite",
                "parameters": [
                    {
                        "description": "Invite accept data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/invite.AcceptInviteRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Invite hash",
                        "name": "inviteHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Campaign is archived, or the character is not the requester's, is already in a campaign or has another game system",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "403": {
                        "description": "The DM can't join their own campaign",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "404": {
                        "description": "Invite not found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/core/api/v1/user": {
            "get": {
                "description": "Get current user profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1:user"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid access_token",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.HttpError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/health": {
            "get": {
                "description": "Check application health status",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "campaign.CampaignCharacterRefResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "campaign.CampaignDetailResponse": {
            "type": "object",
            "properties": {
                "characters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/campaign.CampaignDetailResponseCharacterItem"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "invite_hash": {
                    "type": "string"
                },
                "is_dm": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "campaign.CampaignDetailResponseCharacterItem": {
            "type": "object",
            "properties": {
                "current_hp": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "campaign.CampaignListPageResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/campaign.CampaignListResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "campaign.CampaignListResponse": {
            "type": "object",
            "properties": {
                "is_dm": {
                    "type": "boolean"
                },
                "my_characters": {
                    "description": "The requester characters in the campaign, ordered by name; empty when the requester only runs it",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/campaign.CampaignCharacterRefResponse"
                    }
                },
                "name": {
                    "type": "string"
                },
                "player_count": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "campaign.CampaignStatusCountsResponse": {
            "type": "object",
            "properties": {
                "ACTIVE": {
                    "type": "integer"
                },
                "ARCHIVED": {
                    "type": "integer"
                },
                "DRAFT": {
                    "type": "integer"
                },
                "PAUSED": {
                    "type": "integer"
                }
            }
        },
        "campaign.CampaignStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "campaign.CreateCampaignRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "campaign.UpdateCampaignStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "character.CharacterCurrentHpResponse": {
            "type": "object",
            "properties": {
                "current_hp": {
                    "type": "integer"
                }
            }
        },
        "character.CharacterDetailResponse": {
            "type": "object",
            "properties": {
                "current_hp": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_player": {
                    "type": "boolean"
                },
                "max_hp": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "character.CharacterListPageResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/character.CharacterListResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "character.CharacterListResponse": {
            "type": "object",
            "properties": {
                "current_hp": {
                    "type": "integer"
                },
                "max_hp": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "character.CreateCharacterRequest": {
            "type": "object",
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "character.UpdateHPRequest": {
            "type": "object",
            "properties": {
                "new_hp": {
                    "type": "integer"
                }
            }
        },
        "httperrors.HttpError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "invite.AcceptInviteRequest": {
            "type": "object",
            "properties": {
                "character_slug": {
                    "type": "string"
                }
            }
        },
        "invite.CreateInviteRequest": {
            "type": "object",
            "properties": {
                "campaign_id": {
                    "type": "integer"
                }
            }
        },
        "invite.InviteCreateResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                }
            }
        },
        "invite.InviteDetailsResponse": {
            "type": "object",
            "properties": {
                "campaign_name": {
                    "type": "string"
                },
                "campaign_overview": {
                    "type": "string"
                },
                "campaign_player_count": {
                    "type": "integer"
                },
                "campaign_slug": {
                    "type": "string"
                },
                "campaign_system": {
                    "type": "string"
                },
                "invite_hash": {
                    "type": "string"
                },
                "is_dm": {
                    "type": "boolean"
                }
            }
        },
        "rpg.RpgIdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "rpg.RpgSlugResponse": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string"
                }
            }
        },
        "user.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Questmaster's APIs",
	Description:      "REST APIs of Questmaster for documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
